# Default values for reciper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# version of deployed app images, can be overriden per component
version: ""

# override for nats url ( shared in cluster )
nats_url: ""

# password for optional basic auth on ingress
basicAuthPassword: ""
# used for gql ingress
ingressClassName: "nginx"

api:
  repository: ghcr.io/encero/reciper-api
  pullPolicy: IfNotPresent
  tag: ""
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
gql:
  # hostname for ingress
  host: ""
  repository: ghcr.io/encero/reciper-gql
  pullPolicy: IfNotPresent
  tag: ""
  resources: {}

# enable tls on ingress
tls:
  enabled: false
  # name of the cert issuer resource
  certClusterIssuer: ""
  # name of secret where the private key will be stored
  secretName: ""

# values for nats subchart
nats:
  natsbox:
    enabled: false
  exporter:
    enabled: false