// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewRecipe struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Recipe struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
