// Code generated by entc, DO NOT EDIT.

package cookinghistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/encero/reciper/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CookedAt applies equality check predicate on the "cookedAt" field. It's identical to CookedAtEQ.
func CookedAt(v time.Time) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCookedAt), v))
	})
}

// CookedAtEQ applies the EQ predicate on the "cookedAt" field.
func CookedAtEQ(v time.Time) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCookedAt), v))
	})
}

// CookedAtNEQ applies the NEQ predicate on the "cookedAt" field.
func CookedAtNEQ(v time.Time) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCookedAt), v))
	})
}

// CookedAtIn applies the In predicate on the "cookedAt" field.
func CookedAtIn(vs ...time.Time) predicate.CookingHistory {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CookingHistory(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCookedAt), v...))
	})
}

// CookedAtNotIn applies the NotIn predicate on the "cookedAt" field.
func CookedAtNotIn(vs ...time.Time) predicate.CookingHistory {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CookingHistory(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCookedAt), v...))
	})
}

// CookedAtGT applies the GT predicate on the "cookedAt" field.
func CookedAtGT(v time.Time) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCookedAt), v))
	})
}

// CookedAtGTE applies the GTE predicate on the "cookedAt" field.
func CookedAtGTE(v time.Time) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCookedAt), v))
	})
}

// CookedAtLT applies the LT predicate on the "cookedAt" field.
func CookedAtLT(v time.Time) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCookedAt), v))
	})
}

// CookedAtLTE applies the LTE predicate on the "cookedAt" field.
func CookedAtLTE(v time.Time) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCookedAt), v))
	})
}

// HasRecipe applies the HasEdge predicate on the "recipe" edge.
func HasRecipe() predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RecipeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecipeTable, RecipeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecipeWith applies the HasEdge predicate on the "recipe" edge with a given conditions (other predicates).
func HasRecipeWith(preds ...predicate.Recipe) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RecipeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecipeTable, RecipeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CookingHistory) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CookingHistory) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CookingHistory) predicate.CookingHistory {
	return predicate.CookingHistory(func(s *sql.Selector) {
		p(s.Not())
	})
}
