apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "reciper.fullname" . }}-api"
  labels:
    {{- include "reciper.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "reciper.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "reciper.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      volumes:
        - name: data
      {{- if .Values.litestream.enabled }}
        - name: litestream-configmap
          configMap:
            name: "{{ include "reciper.fullname" . }}-litestream"
      {{end}}
      {{- if .Values.litestream.enabled }}
      initContainers:
      - name: init-litestream
        image: litestream/litestream:0.3.8
        # image: busybox:latest
        args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '{{.Values.api.dbPath}}']
        # command: ['cat','/etc/litestream.yml']
        volumeMounts:
        - name: data
          mountPath: {{ dir .Values.api.dbPath }}
        - name: litestream-configmap
          mountPath: /etc/litestream.yml
          subPath: litestream.yml
        env:
        - name: LITESTREAM_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: litestream
              key: LITESTREAM_ACCESS_KEY_ID
        - name: LITESTREAM_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: litestream
              key: LITESTREAM_SECRET_ACCESS_KEY
      {{end}}
      containers:
        - name: "{{ .Chart.Name }}-api"
          image: "{{.Values.api.repository}}:{{ default .Values.version .Values.api.tag }}"
          imagePullPolicy: {{ .Values.api.pullPolicy }}
          env:
            - name: NATS_URL
              value: {{ default (printf "nats://%s-nats:4222" .Release.Name) .Values.nats_url}}
            - name: DB_FILE
              value: {{default "/db.lite" .Values.api.dbPath}}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: {{ dir .Values.api.dbPath }}
{{- if .Values.litestream.enabled }}
        - name: litestream
          image: litestream/litestream:0.3.8
          args: ['replicate']
          volumeMounts:
          - name: data
            mountPath: {{ dir .Values.api.dbPath }}
          - name: litestream-configmap
            mountPath: /etc/litestream.yml
            subPath: litestream.yml
          env:
          - name: LITESTREAM_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: litestream
                key: LITESTREAM_ACCESS_KEY_ID
          - name: LITESTREAM_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: litestream
                key: LITESTREAM_SECRET_ACCESS_KEY
          ports:
          - name: metrics
            containerPort: 9090
{{end}}