// Code generated by entc, DO NOT EDIT.

package recipe

const (
	// Label holds the string label denoting the recipe type in the database.
	Label = "recipe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldPlanned holds the string denoting the planned field in the database.
	FieldPlanned = "planned"
	// EdgeHistory holds the string denoting the history edge name in mutations.
	EdgeHistory = "history"
	// Table holds the table name of the recipe in the database.
	Table = "recipes"
	// HistoryTable is the table that holds the history relation/edge.
	HistoryTable = "cooking_histories"
	// HistoryInverseTable is the table name for the CookingHistory entity.
	// It exists in this package in order to avoid circular dependency with the "cookinghistory" package.
	HistoryInverseTable = "cooking_histories"
	// HistoryColumn is the table column denoting the history relation/edge.
	HistoryColumn = "recipe_history"
)

// Columns holds all SQL columns for recipe fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldPlanned,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlanned holds the default value on creation for the "planned" field.
	DefaultPlanned bool
)
