// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/encero/reciper/ent/cookinghistory"
	"github.com/encero/reciper/ent/predicate"
)

// CookingHistoryDelete is the builder for deleting a CookingHistory entity.
type CookingHistoryDelete struct {
	config
	hooks    []Hook
	mutation *CookingHistoryMutation
}

// Where appends a list predicates to the CookingHistoryDelete builder.
func (chd *CookingHistoryDelete) Where(ps ...predicate.CookingHistory) *CookingHistoryDelete {
	chd.mutation.Where(ps...)
	return chd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (chd *CookingHistoryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(chd.hooks) == 0 {
		affected, err = chd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CookingHistoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			chd.mutation = mutation
			affected, err = chd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(chd.hooks) - 1; i >= 0; i-- {
			if chd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = chd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, chd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (chd *CookingHistoryDelete) ExecX(ctx context.Context) int {
	n, err := chd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (chd *CookingHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: cookinghistory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: cookinghistory.FieldID,
			},
		},
	}
	if ps := chd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, chd.driver, _spec)
}

// CookingHistoryDeleteOne is the builder for deleting a single CookingHistory entity.
type CookingHistoryDeleteOne struct {
	chd *CookingHistoryDelete
}

// Exec executes the deletion query.
func (chdo *CookingHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := chdo.chd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cookinghistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (chdo *CookingHistoryDeleteOne) ExecX(ctx context.Context) {
	chdo.chd.ExecX(ctx)
}
