version: "3.9"
   
services:
  nats:
    image: nats:2.7-alpine
    restart: always
  api:
    build:
      context: ../
      dockerfile: docker/go.Dockerfile
      args:
        build_target: cmd/api/api.go
    environment:
      - NATS_URL=nats://nats:4222
      - LOGGER=dev
    restart: always
    depends_on:
      - nats
  gql:
    build:
      context: ../
      dockerfile: docker/go.Dockerfile
      args:
        build_target: gql/server.go
    image: reciper-gql:latest
    environment:
      - NATS_URL=nats://nats:4222
      - LOGGER=dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - nats
        
